GET http://localhost:5000/account
###
GET http://localhost:5000/account
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
###
POST http://localhost:5000/account
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "birthdate": "2015-01-01"
}
###
PATCH http://localhost:5000/account/2
Content-Type: application/json

{
    "username": "JohnDoe"
}
###
DELETE http://localhost:5000/account/2
###
